### ISSUE TITLE
EPIC: bank Contract

### ISSUE THREAD

**Issue by GrandGarcon** [DeBond-Protocol/main#3]
# Description
Bank contract  is used  for issuing  DBGT / DBIT  bonds , minting Vote contracts  etc.
 
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
 testing the functions.

- [ ]  buyVoteTokensByDBGT();
- [ ] getPriceExchangeDBITByDBGT();

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
